### ISSUE TITLE
using HTTP api versus Python interface in provider implementation

### ISSUE THREAD

**Issue by cosenal** [CenterForOpenScience/waterbutler#38]
As far as I understand, for the Dropbox provider, the [HTTP api](https://www.dropbox.com/developers/core/docs) is used directly instead of the [Python interface](https://www.dropbox.com/developers/core/docs/python). I suppose it's because you want more control, but what's the exact reason for that? 

Do you suggest to do the same for the ownCloud provider? I am asking because I was planning to use [Python ownCloud library](ownCloud client library for Python). Should I use the HTTP WebDAV api directly?

cc @chrisseto

**Comment by JeffSpies** [comment]
@chrisseto will need to respond, but I believe use of the python interface was a bit less efficient because of the needed asynchrony. That may be something you can fork into the ownCloud library, or something you feel is just easier to attain with the WebDAV API.

**Comment by chrisseto** [comment]
@cosenal, @JeffSpies is correct.
We don't use python client libraries because they are all written synchronously which undermines all benefits that WaterButler provides.
Most client libraries are just a thin wrapper around the HTTP API that provide convenience methods.

I would suggest forgoing the python library and just using the helpers the provider class has built in for creating urls.

**Comment by cosenal** [comment]
@chrisseto @JeffSpies Thanks for the answers, I will go straight for the HTTP api. It should be easy enough by looking inside the implementation of the python library itself.
Btw, is there a COS mailing list where I can ask this kind of questions that are not really issues?
